-- CSV file format for Crunchbase data ingestion
-- Co-authored with CoCo

USE ROLE CRUNCHBASE_LOADER;
USE WAREHOUSE CRUNCHBASE_INGEST_WH;
USE DATABASE CRUNCHBASE_RAW;
USE SCHEMA ingestion;

CREATE OR REPLACE FILE FORMAT crunchbase_csv_format
TYPE=csv
COMPRESSION=auto
FIELD_DELIMITER=','
RECORD_DELIMITER='\n'
SKIP_HEADER=1
FIELD_OPTIONALLY_ENCLOSED_BY='"'
TRIM_SPACE=FALSE
ERROR_ON_COLUMN_COUNT_MISMATCH=TRUE
REPLACE_INVALID_CHARACTERS=FALSE
SKIP_BLANK_LINES=TRUE
EMPTY_FIELD_AS_NULL=TRUE
NULL_IF=('','NULL','null','\\N','None','none')
ENCODING='UTF8'
COMMENT='CSV format for the crunchbase practice dataset';